### ISSUE TITLE
Utwory z # w tytule się nie pobierają

### ISSUE THREAD

**Issue by hrw** [hrw/modland-player#11]
Hoffmann - Protracker/comic bakery #1.mod na przykład.

**Comment by hrw** [comment]
Wybranie takiego utworu przerywa odtwarzanie ale zostawia info o module załadowanym poprzednio. Przyciski są ignorowane.

**Comment by hrw** [comment]
To samo jak się wybierze "coop" jakiś. 

Hoffman też.

**Comment by michalsc** [comment]
Poprawione w e52af231, jezeli chodzi o # w URL.
